name: moordemo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  get_it: ^5.0.3
  moor_flutter: ^4.0.0
  path_provider: ^1.6.24
  flutter_bloc: ^7.0.1
  sqlite3_flutter_libs: ^0.5.0
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.3.1
  build_runner: ^1.10.4
  build_web_compilers: ^2.3.0

